### ISSUE TITLE
能出一个exe版本吗

### ISSUE THREAD

**Issue by zippno** [Verlif/windonly#1]
尝试把代码clone下来，跑不动，jdk版本是用的哪个呢？

**Comment by Verlif** [comment]
JDK用的是17。
exe的话也可以，但是最近我想加入局域网工作区功能，可能要几天之后了。

**Comment by zippno** [comment]
持续关注，支持作者，希望能release一个exe可直接执行的版本，自己拉代码打包的话，有几个你自己封装的包依赖找不到，再此感谢！

**Comment by Verlif** [comment]
> 持续关注，支持作者，希望能release一个exe可直接执行的版本，自己拉代码打包的话，有几个你自己封装的包依赖找不到，再此感谢！

OK，这两天我搞一个

**Comment by Verlif** [comment]
哈哈哈哈哈，用jlink和jpackage终于弄好了，现在有exe可以用了。在发布包里面。
